# .github/workflows/update-readme.yml
name: Update README

on:
  schedule:
    - cron: '0 1 * * 1'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: pip install requests
      - name: Run script
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: python update_readme.py
      - name: Commit and push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add README.md
          git commit -m "Update contributed repositories"
          git push
