name: Update README

on:
  schedule:
    - cron: '0 0 * * *' # 毎日0時
  workflow_dispatch:

permissions:
  contents: write  # ←これを必ず追加！

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests

      - name: Run script
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: python update_readme.py

      - name: Commit and push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add README.md
          git commit -m "Update contributed repositories" || echo "No changes to commit"
          git push
